"""Diagnostics Store 端口."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import RuntimeDiagnostic, SchedulerDiagnostic, TaskDiagnostic


@runtime_checkable
class DiagnosticStore(Protocol):
    def get_runtime(self) -> RuntimeDiagnostic | None: ...
    def set_runtime(self, diagnostic: RuntimeDiagnostic) -> None: ...

    def get_scheduler(self) -> SchedulerDiagnostic | None: ...
    def set_scheduler(self, diagnostic: SchedulerDiagnostic) -> None: ...

    def get_task(self, task_id: int) -> TaskDiagnostic | None: ...
    def set_task(self, diagnostic: TaskDiagnostic) -> None: ...
    def list_tasks(self) -> tuple[TaskDiagnostic, ...]: ...

    def clear(self) -> None: ...
