"""init whale schema

Revision ID: eb5d458b81c8
Revises: 
Create Date: 2026-06-29 21:32:55.740030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5d458b81c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    """Upgrade schema."""
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    """Downgrade schema."""
    globals()["downgrade_%s" % engine_name]()





def upgrade_whale() -> None:
    """Upgrade whale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('asset_type_id', sa.Integer(), autoincrement=True, nullable=False, comment='资产类型主键'),
    sa.Column('type_code', sa.String(length=64), nullable=False, comment='资产类型编码，如 WIND_FARM / COLLECTOR_LINE / WTG / BOX_TRANSFORMER / PCS / BMS / SVG / MET_STATION / GATEWAY / BLADE / GENERATOR / CONVERTER'),
    sa.Column('type_name', sa.String(length=255), nullable=False, comment='资产类型名称，如 风场 / 集电线 / 风力发电机组 / 箱变 / 储能PCS / 通信管理机 / 叶片'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='资产大类：SITE / ELECTRICAL_DEVICE / GENERATION_DEVICE / STORAGE_DEVICE / COMMUNICATION_DEVICE / COMPONENT'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='资产类型说明'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展属性，如是否允许挂接部件、是否允许作为拓扑节点、默认图标、默认层级等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('asset_type_id'),
    sa.UniqueConstraint('type_code', name='uq_asset_type_code'),
    comment='资产类型'
    )
    op.create_table('ingest_audit_event',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('before_version', sa.Integer(), nullable=True),
    sa.Column('after_version', sa.Integer(), nullable=True),
    sa.Column('changed_fields_json', sa.JSON(), nullable=False),
    sa.Column('attributes_json', sa.JSON(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_ingest_audit_event_request_id'), 'ingest_audit_event', ['request_id'], unique=False)
    op.create_table('ingest_bundle_metadata',
    sa.Column('bundle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bundle_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('signature_status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('bundle_id'),
    sa.UniqueConstraint('bundle_version')
    )
    op.create_table('ingest_fencing_token',
    sa.Column('token_name', sa.String(length=255), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token_name')
    )
    op.create_table('ingest_idempotency_record',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_ingest_idempotency_record_idempotency_key'), 'ingest_idempotency_record', ['idempotency_key'], unique=True)
    op.create_table('ingest_job_lease',
    sa.Column('lease_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lease_name', sa.String(length=255), nullable=False),
    sa.Column('lease_scope', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('holder_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fencing_token', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('renewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('lease_id'),
    sa.UniqueConstraint('lease_name', name='uq_ingest_job_lease_name')
    )
    op.create_index(op.f('ix_ingest_job_lease_holder_key'), 'ingest_job_lease', ['holder_key'], unique=False)
    op.create_index(op.f('ix_ingest_job_lease_resource_id'), 'ingest_job_lease', ['resource_id'], unique=False)
    op.create_table('ingest_runtime_config_version',
    sa.Column('config_version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('accepted_bundle_version', sa.String(length=64), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_version_id'),
    sa.UniqueConstraint('scope', name='uq_ingest_runtime_config_version_scope')
    )
    op.create_table('ingest_runtime_node',
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('runtime_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('node_key')
    )
    op.create_table('org_unit',
    sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False, comment='组织名称'),
    sa.Column('parent_org_id', sa.Integer(), nullable=True, comment='上级组织ID'),
    sa.ForeignKeyConstraint(['parent_org_id'], ['org_unit.org_id'], ),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('org_name'),
    comment='组织（集团/大区/电场）'
    )
    op.create_index(op.f('ix_org_unit_parent_org_id'), 'org_unit', ['parent_org_id'], unique=False)
    op.create_table('scada_cdc_dict',
    sa.Column('cdc_id', sa.Integer(), autoincrement=True, nullable=False, comment='CDC 主键'),
    sa.Column('cdc_code', sa.String(length=8), nullable=False, comment='CDC 编码：MV / SPS / INS / ACT / DPC 等'),
    sa.Column('cdc_name', sa.String(length=64), nullable=False, comment='CDC 英文全称'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='中文说明'),
    sa.PrimaryKeyConstraint('cdc_id'),
    sa.UniqueConstraint('cdc_code'),
    sa.UniqueConstraint('cdc_code', name='uq_cdc_code'),
    comment='CDC 字典'
    )
    op.create_table('scada_data_type',
    sa.Column('data_type_id', sa.Integer(), autoincrement=True, nullable=False, comment='数据类型主键'),
    sa.Column('type_name', sa.String(length=64), nullable=False, comment='类型名称：BOOLEAN / INT32 / INT64 / FLOAT32 / FLOAT64 / STRING / DATETIME / JSON'),
    sa.Column('encoding', sa.String(length=128), nullable=True, comment='编码方式：IEC61850_BASIC / OPCUA_VARIANT / MODBUS_REGISTER'),
    sa.Column('size_bits', sa.Integer(), nullable=True, comment='位宽'),
    sa.Column('constraint_expr', sa.String(length=255), nullable=True, comment='值域约束 SQL 条件语句，如 CHECK(value BETWEEN -3.4E38 AND 3.4E38) / CHECK(value IN (0,1)) / CHECK(LENGTH(value) <= 255)'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展信息，如 协议类型映射、序列化规则'),
    sa.PrimaryKeyConstraint('data_type_id'),
    sa.UniqueConstraint('type_name'),
    sa.UniqueConstraint('type_name', name='uq_data_type_name'),
    comment='SCADA 数据类型'
    )
    op.create_table('scada_fc_dict',
    sa.Column('fc_id', sa.Integer(), autoincrement=True, nullable=False, comment='FC 主键'),
    sa.Column('fc_code', sa.String(length=8), nullable=False, comment='FC 编码：ST / MX / SP / SV / CF / DC / EX'),
    sa.Column('fc_name', sa.String(length=64), nullable=False, comment='FC 英文全称'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='中文说明'),
    sa.PrimaryKeyConstraint('fc_id'),
    sa.UniqueConstraint('fc_code'),
    sa.UniqueConstraint('fc_code', name='uq_fc_code'),
    comment='FC 字典'
    )
    op.create_table('scada_protocol_param_def',
    sa.Column('param_def_id', sa.Integer(), autoincrement=True, nullable=False, comment='参数定义主键'),
    sa.Column('application_protocol', sa.String(length=64), nullable=False, comment='应用层协议族：OPC_UA / MODBUS / IEC101 / IEC104 / IEC61850 / MQTT / HTTP_REST / BECKHOFF_ADS。新增协议时继续扩此枚举，不为每个协议复制新表。'),
    sa.Column('service_type', sa.String(length=64), nullable=True, comment='服务类型：READ / SUBSCRIBE / TCP_READ / RTU_READ / INTERROGATION / SPONTANEOUS / MMS_READ / REPORT / GOOSE / SV / REQUEST / ADS_READ_WRITE / ADS_NOTIFICATION 等；为 None 表示该参数适用于同协议全部服务。'),
    sa.Column('transport', sa.String(length=32), nullable=True, comment='传输层：TCP / SERIAL / ETHERNET_L2 / MQTT / HTTP / HTTPS；None 表示适用于同协议全部传输，避免为每种 transport 复制参数定义表。'),
    sa.Column('param_key', sa.String(length=128), nullable=False, comment='参数键，如 network_interface / vlan_id / app_id / unit_id / baudrate'),
    sa.Column('param_name', sa.String(length=255), nullable=False, comment='参数中文名称'),
    sa.Column('data_type', sa.String(length=64), nullable=False, comment='数据类型：STRING / INT / FLOAT / BOOL'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('default_value', sa.String(length=512), nullable=True, comment='默认值（字符串表示）'),
    sa.Column('unit', sa.String(length=64), nullable=True, comment='单位，如 ms / bps / Hz'),
    sa.Column('allowed_values', sa.String(length=1024), nullable=True, comment='允许值列表，逗号分隔；供 Navicat 下拉和值域核对'),
    sa.Column('constraint_expr', sa.String(length=512), nullable=True, comment='约束表达式，如 value > 0 / 0 <= value <= 100'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='参数说明；描述该定义在多协议矩阵中的语义和约束，不存具体 endpoint 值'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('param_def_id'),
    sa.UniqueConstraint('application_protocol', 'service_type', 'transport', 'param_key', name='uq_protocol_param_def'),
    comment='协议端点参数定义'
    )
    op.create_table('scada_signal_param_def',
    sa.Column('param_def_id', sa.Integer(), autoincrement=True, nullable=False, comment='信号参数定义主键'),
    sa.Column('application_protocol', sa.String(length=64), nullable=False, comment='应用层协议族：与 endpoint 参数定义保持一致。通过协议+服务矩阵描述同一套共享点表在不同协议下的寻址方式。'),
    sa.Column('service_type', sa.String(length=64), nullable=True, comment='服务类型；None 表示适用于同协议全部服务。可用来区分如 ADS_READ_WRITE 与 ADS_NOTIFICATION 的寻址/订阅参数差异。'),
    sa.Column('param_key', sa.String(length=128), nullable=False, comment='参数键'),
    sa.Column('param_name', sa.String(length=255), nullable=False, comment='参数中文名称'),
    sa.Column('data_type', sa.String(length=64), nullable=False, comment='数据类型：STRING / INT / FLOAT / BOOL / ENUM'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('default_value', sa.String(length=512), nullable=True, comment='默认值'),
    sa.Column('unit', sa.String(length=64), nullable=True, comment='单位'),
    sa.Column('allowed_values', sa.String(length=1024), nullable=True, comment='允许值列表，逗号分隔；供 Navicat 查看可选枚举'),
    sa.Column('constraint_expr', sa.String(length=512), nullable=True, comment='约束表达式'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='参数说明；描述共享 signal_profile_item 在该协议/服务下如何被定位或订阅'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('param_def_id'),
    sa.UniqueConstraint('application_protocol', 'service_type', 'param_key', name='uq_signal_param_def'),
    comment='协议信号参数定义'
    )
    op.create_table('simulation_artifact',
    sa.Column('simulation_artifact_id', sa.Integer(), autoincrement=True, nullable=False, comment='仿真制品主键'),
    sa.Column('owner_type', sa.String(length=32), nullable=False, comment='所属对象类型：MODEL_ASSET / SIMULATION_CASE / SIMULATION_RESULT'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='所属对象 ID'),
    sa.Column('artifact_type', sa.String(length=32), nullable=False, comment='制品类型：SOURCE_FILE / INPUT_FILE / RESULT_FILE / REPORT / LOG / CONFIG / OTHER'),
    sa.Column('file_uri', sa.String(length=1024), nullable=False, comment='文件 URI'),
    sa.Column('raw_archive_batch_id', sa.String(length=128), nullable=True, comment='原始归档批次 ID'),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='文件 SHA256 校验和'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('simulation_artifact_id'),
    comment='仿真制品'
    )
    op.create_table('topology_graph',
    sa.Column('topology_id', sa.Integer(), autoincrement=True, nullable=False, comment='拓扑图主键'),
    sa.Column('topology_code', sa.String(length=128), nullable=False, comment='拓扑编码，如 ELECTRICAL_TOPOLOGY / NETWORK_TOPOLOGY / ASSET_TREE / CONTROL_TOPOLOGY'),
    sa.Column('topology_name', sa.String(length=255), nullable=False, comment='拓扑名称，如 电气拓扑 / 通信网络拓扑 / 资产层级拓扑'),
    sa.Column('topology_type', sa.String(length=32), nullable=False, comment='拓扑类型：ELECTRICAL / NETWORK / PHYSICAL / CONTROL'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='拓扑说明'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='拓扑扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('topology_id'),
    sa.UniqueConstraint('topology_code'),
    comment='拓扑图定义'
    )
    op.create_table('asset_attribute',
    sa.Column('attribute_id', sa.Integer(), autoincrement=True, nullable=False, comment='属性定义主键'),
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='所属资产类型'),
    sa.Column('attribute_name', sa.String(length=128), nullable=False, comment='属性名，也是 asset_model.specifications 中的 JSON key，如 rated_power_kw / hub_height_m / rotor_diameter_m'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='显示名称，如 额定功率 / 轮毂高度 / 叶轮直径'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='属性含义说明'),
    sa.Column('data_type_id', sa.Integer(), nullable=True, comment='数据类型 ID'),
    sa.Column('unit', sa.String(length=64), nullable=True, comment='单位，如 kW / m / V / A / %'),
    sa.Column('constraint_expr', sa.String(length=255), nullable=True, comment='约束表达式，如 value > 0 / 0 <= value <= 100'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='该型号属性是否必填'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展信息'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['data_type_id'], ['scada_data_type.data_type_id'], ),
    sa.PrimaryKeyConstraint('attribute_id'),
    sa.UniqueConstraint('asset_type_id', 'attribute_name', name='uq_asset_attribute_type_name'),
    comment='资产型号属性定义'
    )
    op.create_table('asset_model',
    sa.Column('model_id', sa.Integer(), autoincrement=True, nullable=False, comment='资产型号主键'),
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='所属资产类型'),
    sa.Column('model_code', sa.String(length=128), nullable=False, comment='型号编码，如 WTG_5MW_VENDOR_A / PCS_2500KW_VENDOR_B / BLADE_85M_VENDOR_C'),
    sa.Column('model_name', sa.String(length=255), nullable=False, comment='型号名称'),
    sa.Column('manufacturer', sa.String(length=255), nullable=True, comment='制造商'),
    sa.Column('specifications', sa.JSON(), nullable=False, comment='型号技术参数 JSON，如 {"rated_power_kw": 5000, "hub_height_m": 120, "rotor_diameter_m": 190}'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='型号说明'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展信息，如资料来源、参数版本、厂家私有字段'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('asset_type_id', 'model_code', name='uq_asset_model_type_code'),
    comment='资产型号'
    )
    op.create_table('scada_signal_profile',
    sa.Column('signal_profile_id', sa.Integer(), autoincrement=True, nullable=False, comment='点位方案主键'),
    sa.Column('profile_code', sa.String(length=128), nullable=False, comment='点位方案编码，如 WTG_IEC61400_25_BASIC_V1'),
    sa.Column('profile_name', sa.String(length=255), nullable=False, comment='点位方案名称，如 风机基础采集点位方案 V1'),
    sa.Column('asset_type_id', sa.Integer(), nullable=True, comment='适用资产类型'),
    sa.Column('standard_family', sa.String(length=64), nullable=True, comment='标准体系：IEC61400_25 / IEC61850 / GB_T_30966 / VENDOR_PRIVATE'),
    sa.Column('vendor', sa.String(length=128), nullable=True, comment='厂家：STANDARD / VendorA / VendorB'),
    sa.Column('version', sa.String(length=32), nullable=True, comment='方案版本'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='方案说明'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='方案扩展信息，如 来源文件、适用机型、适用协议、点表版本'),
    sa.Column('record_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观并发版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.PrimaryKeyConstraint('signal_profile_id'),
    sa.UniqueConstraint('profile_code'),
    sa.UniqueConstraint('profile_code', name='uq_signal_profile_code'),
    comment='点位方案'
    )
    op.create_table('asset_bom',
    sa.Column('bom_id', sa.Integer(), autoincrement=True, nullable=False, comment='BOM 主键'),
    sa.Column('parent_asset_type_id', sa.Integer(), nullable=False, comment='父资产类型 ID'),
    sa.Column('parent_model_id', sa.Integer(), nullable=False, comment='父资产型号 ID'),
    sa.Column('child_asset_type_id', sa.Integer(), nullable=False, comment='子资产类型 ID'),
    sa.Column('child_model_id', sa.Integer(), nullable=True, comment='子资产型号 ID，可为空'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量'),
    sa.Column('required', sa.Boolean(), nullable=False, comment='是否必选部件'),
    sa.Column('position_rule', sa.String(length=255), nullable=True, comment='部件位置规则，如 BLADE_A / BLADE_B / BLADE_C'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展属性'),
    sa.ForeignKeyConstraint(['child_asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['child_model_id'], ['asset_model.model_id'], ),
    sa.ForeignKeyConstraint(['parent_asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['parent_model_id'], ['asset_model.model_id'], ),
    sa.PrimaryKeyConstraint('bom_id'),
    sa.UniqueConstraint('parent_model_id', 'child_asset_type_id', 'child_model_id', 'position_rule', name='uq_asset_bom'),
    comment='资产型号 BOM'
    )
    op.create_table('asset_instance',
    sa.Column('asset_instance_id', sa.Integer(), autoincrement=True, nullable=False, comment='资产实例主键'),
    sa.Column('asset_code', sa.String(length=128), nullable=False, comment='资产编码，如 WF_001 / LINE_A / WTG_001 / PCS_001 / GATEWAY_001 / WTG_001_BLADE_A'),
    sa.Column('asset_name', sa.String(length=255), nullable=False, comment='资产名称，如 一号风场 / A集电线 / 1号风机 / 1号通信管理机 / 1号风机A叶片'),
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='资产类型 ID'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='资产型号 ID，可为空；场站层级、线路层级、虚拟资产可能没有具体型号'),
    sa.Column('org_id', sa.Integer(), nullable=True, comment='所属组织 ID'),
    sa.Column('parent_asset_instance_id', sa.Integer(), nullable=True, comment='父资产实例 ID，支持资产树查询，如 风场→集电线→风机→叶片'),
    sa.Column('installation_date', sa.DateTime(), nullable=True, comment='安装日期'),
    sa.Column('commissioning_date', sa.DateTime(), nullable=True, comment='投运日期'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='安装位置文本，如 A区3号机位'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='纬度'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='资产状态：ACTIVE / INACTIVE / RETIRED / MAINTENANCE'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='资产实例扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['asset_model.model_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org_unit.org_id'], ),
    sa.ForeignKeyConstraint(['parent_asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.PrimaryKeyConstraint('asset_instance_id'),
    sa.UniqueConstraint('asset_code'),
    sa.UniqueConstraint('asset_code', name='uq_asset_instance_code'),
    comment='资产实例'
    )
    op.create_index(op.f('ix_asset_instance_asset_type_id'), 'asset_instance', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_instance_parent_asset_instance_id'), 'asset_instance', ['parent_asset_instance_id'], unique=False)
    op.create_table('scada_signal_profile_item',
    sa.Column('profile_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='点位方案明细主键'),
    sa.Column('signal_profile_id', sa.Integer(), nullable=False, comment='所属点位方案'),
    sa.Column('ln_class', sa.String(length=64), nullable=True, comment='LN 类：MMXU / WROT / WGEN / WTUR / GGIO 等'),
    sa.Column('ln_name', sa.String(length=255), nullable=True, comment='LN 完整名称，如 MMXU1 / WROT1 / WGEN1'),
    sa.Column('do_name', sa.String(length=255), nullable=False, comment='DO 名称，如 TotW / WSpd / Beh / Health / RotSpd'),
    sa.Column('da_name', sa.String(length=128), nullable=True, comment='DA 名称，如 mag.f / stVal / q / t'),
    sa.Column('relative_path', sa.String(length=512), nullable=False, comment='相对于 LD 实例的点位路径，如 MMXU1.TotW.mag.f / WROT1.RotSpd.mag.f'),
    sa.Column('fc', sa.String(length=8), nullable=True, comment='功能约束：ST / MX / SP / CF / DC / EX'),
    sa.Column('cdc', sa.String(length=8), nullable=True, comment='公共数据类：MV / SPS / INS / ACT / DPC'),
    sa.Column('data_type_id', sa.Integer(), nullable=False, comment='数据类型 ID'),
    sa.Column('default_unit', sa.String(length=64), nullable=True, comment='默认单位，如 kW / m/s / ℃ / % / rpm'),
    sa.Column('default_scale', sa.Float(), nullable=True, comment='默认倍率'),
    sa.Column('default_offset', sa.Float(), nullable=True, comment='默认偏移量'),
    sa.Column('default_precision', sa.Integer(), nullable=True, comment='默认小数精度'),
    sa.Column('default_constraint_expr', sa.String(length=255), nullable=True, comment='默认值域或约束表达式，如 0 <= value <= 100 / value >= 0 / NONE'),
    sa.Column('default_sample_mode', sa.String(length=32), nullable=False, comment='默认采样模式：POLLING / SUBSCRIPTION / REPORT'),
    sa.Column('default_sample_interval_ms', sa.Integer(), nullable=False, comment='默认采样周期，单位毫秒'),
    sa.Column('default_deadband', sa.Float(), nullable=True, comment='默认死区'),
    sa.Column('quality_supported', sa.Boolean(), nullable=False, comment='该点位是否支持质量位'),
    sa.Column('timestamp_supported', sa.Boolean(), nullable=False, comment='该点位是否支持源端时间戳'),
    sa.Column('writable', sa.Boolean(), nullable=False, comment='是否可写或可控'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='显示名称，如 有功功率 / 风速 / 转速 / 运行状态'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='点位说明'),
    sa.Column('record_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观并发版本号'),
    sa.ForeignKeyConstraint(['data_type_id'], ['scada_data_type.data_type_id'], ),
    sa.ForeignKeyConstraint(['signal_profile_id'], ['scada_signal_profile.signal_profile_id'], ),
    sa.PrimaryKeyConstraint('profile_item_id'),
    sa.UniqueConstraint('signal_profile_id', 'relative_path', name='uq_profile_item_path'),
    comment='点位方案明细'
    )
    op.create_index(op.f('ix_scada_signal_profile_item_signal_profile_id'), 'scada_signal_profile_item', ['signal_profile_id'], unique=False)
    op.create_table('asset_relation',
    sa.Column('relation_id', sa.Integer(), autoincrement=True, nullable=False, comment='资产关系主键'),
    sa.Column('source_asset_instance_id', sa.Integer(), nullable=False, comment='源资产实例 ID'),
    sa.Column('target_asset_instance_id', sa.Integer(), nullable=False, comment='目标资产实例 ID'),
    sa.Column('relation_type', sa.String(length=64), nullable=False, comment='关系类型：PARENT_CHILD / ELECTRICAL_CONNECTED_TO / COMMUNICATION_PROXY_FOR / MEASURES / INSTALLED_IN / CONTROLS / PROTECTS'),
    sa.Column('direction', sa.String(length=16), nullable=False, comment='关系方向：DIRECTED / UNDIRECTED'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='关系生效时间'),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True, comment='关系失效时间'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展信息，如连接端子、线路编号、代理协议、测量范围'),
    sa.ForeignKeyConstraint(['source_asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['target_asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.PrimaryKeyConstraint('relation_id'),
    sa.UniqueConstraint('source_asset_instance_id', 'target_asset_instance_id', 'relation_type', 'valid_from', name='uq_asset_relation'),
    comment='资产关系'
    )
    op.create_table('model_asset',
    sa.Column('model_asset_id', sa.Integer(), autoincrement=True, nullable=False, comment='模型资产主键'),
    sa.Column('model_code', sa.String(length=128), nullable=False, comment='模型编码，全局唯一，如 MY_FARM_FAST_v1'),
    sa.Column('model_name', sa.String(length=255), nullable=False, comment='模型名称，如 某风场FAST模型'),
    sa.Column('model_type', sa.String(length=32), nullable=False, comment='模型类型：FAST / OPENFAST / WINDFARM / BLADED / SIMULINK / OTHER'),
    sa.Column('asset_scope', sa.String(length=32), nullable=False, comment='资产范围：SITE / WIND_FARM / WTG / COMPONENT / STORAGE / GRID / OTHER'),
    sa.Column('owner_asset_instance_id', sa.Integer(), nullable=True, comment='所属资产实例 ID，可空（纯设计模型）'),
    sa.Column('parent_model_asset_id', sa.Integer(), nullable=True, comment='父模型资产 ID，支持模型版本/派生关系'),
    sa.Column('source_file_uri', sa.String(length=1024), nullable=True, comment='源文件 URI（存储路径或对象存储 key）'),
    sa.Column('raw_archive_batch_id', sa.String(length=128), nullable=True, comment='原始归档批次 ID'),
    sa.Column('version', sa.String(length=64), nullable=False, comment='模型版本号'),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='主文件 SHA256 校验和'),
    sa.Column('parser_status', sa.String(length=32), nullable=False, comment='解析状态：IMPORTED / PARTIAL / UNSUPPORTED / FAILED'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据，如模型描述、仿真参数、文件列表等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['parent_model_asset_id'], ['model_asset.model_asset_id'], ),
    sa.PrimaryKeyConstraint('model_asset_id'),
    sa.UniqueConstraint('model_code', name='uq_model_asset_code'),
    comment='模型资产'
    )
    op.create_table('scada_ied',
    sa.Column('ied_id', sa.Integer(), autoincrement=True, nullable=False, comment='IED 主键'),
    sa.Column('asset_instance_id', sa.Integer(), nullable=False, comment='IED 所属资产实例，不能为空'),
    sa.Column('ied_name', sa.String(length=255), nullable=False, comment='IED 名称，如 IED_WTG_001 / IED_GATEWAY_001 / IED_PCS_001'),
    sa.Column('ied_code', sa.String(length=128), nullable=True, comment='IED 编码，如 WTG001_CTRL_IED / GATEWAY_A_IED'),
    sa.Column('ied_type', sa.String(length=64), nullable=True, comment='IED 类型：WTG_CONTROLLER / SUBSTATION_GATEWAY / PCS_CONTROLLER / MET_STATION / PROTECTION_DEVICE'),
    sa.Column('standard_family', sa.String(length=64), nullable=True, comment='标准体系：IEC61850 / IEC61400_25 / DLT860 / GB_T_30966 / VENDOR_PRIVATE'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='IED 扩展属性，如 SCL 来源文件、工程版本、厂家私有标识'),
    sa.Column('record_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观并发版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.PrimaryKeyConstraint('ied_id'),
    sa.UniqueConstraint('ied_name'),
    sa.UniqueConstraint('ied_name', name='uq_ied_name'),
    comment='IED 实例'
    )
    op.create_index(op.f('ix_scada_ied_asset_instance_id'), 'scada_ied', ['asset_instance_id'], unique=False)
    op.create_table('scada_signal_profile_item_param_value',
    sa.Column('item_param_id', sa.Integer(), autoincrement=True, nullable=False, comment='信号参数值主键'),
    sa.Column('profile_item_id', sa.Integer(), nullable=False, comment='点位方案明细 ID；多个协议服务可复用同一 profile_item，并分别写参数值'),
    sa.Column('param_def_id', sa.Integer(), nullable=False, comment='信号参数定义 ID；通过定义表区分协议/服务，不复制多套 signal_profile_item'),
    sa.Column('value_text', sa.String(length=2048), nullable=True, comment='参数值（文本）'),
    sa.Column('value_int', sa.Integer(), nullable=True, comment='参数值（整数）'),
    sa.Column('value_float', sa.Float(), nullable=True, comment='参数值（浮点数）'),
    sa.Column('value_bool', sa.Boolean(), nullable=True, comment='参数值（布尔）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['param_def_id'], ['scada_signal_param_def.param_def_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_item_id'], ['scada_signal_profile_item.profile_item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_param_id'),
    sa.UniqueConstraint('profile_item_id', 'param_def_id', name='uq_signal_param_value'),
    comment='点位方案明细协议参数值'
    )
    op.create_index(op.f('ix_scada_signal_profile_item_param_value_profile_item_id'), 'scada_signal_profile_item_param_value', ['profile_item_id'], unique=False)
    op.create_table('topology_node',
    sa.Column('node_id', sa.Integer(), autoincrement=True, nullable=False, comment='拓扑节点主键'),
    sa.Column('topology_id', sa.Integer(), nullable=False, comment='所属拓扑图 ID'),
    sa.Column('asset_instance_id', sa.Integer(), nullable=False, comment='关联资产实例 ID'),
    sa.Column('node_code', sa.String(length=128), nullable=True, comment='拓扑节点编码，如 WTG_001_NODE / BOX_001_NODE / SWITCH_A_NODE'),
    sa.Column('node_name', sa.String(length=255), nullable=True, comment='拓扑节点名称'),
    sa.Column('node_role', sa.String(length=64), nullable=True, comment='节点角色：SOURCE / LOAD / SWITCH / TRANSFORMER / ROUTER / GATEWAY / TERMINAL'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='节点扩展信息，如 图形坐标、电压等级、网络区域'),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['topology_id'], ['topology_graph.topology_id'], ),
    sa.PrimaryKeyConstraint('node_id'),
    sa.UniqueConstraint('topology_id', 'asset_instance_id', name='uq_topology_node'),
    comment='拓扑节点'
    )
    op.create_table('scada_communication_endpoint',
    sa.Column('endpoint_id', sa.Integer(), autoincrement=True, nullable=False, comment='通信端点主键'),
    sa.Column('ied_id', sa.Integer(), nullable=False, comment='所属 IED'),
    sa.Column('access_point_name', sa.String(length=128), nullable=False, comment='AccessPoint 名称，如 AP1 / MMS_AP / OPCUA_AP / ETH1'),
    sa.Column('endpoint_name', sa.String(length=255), nullable=True, comment='端点显示名称，如 1号风机MMS端点 / 1号网关OPC UA端点'),
    sa.Column('application_protocol', sa.String(length=64), nullable=False, comment='应用层协议：OPC_UA / MODBUS / IEC101 / IEC104 / IEC61850 / MQTT / HTTP_REST / BECKHOFF_ADS；此列只标识协议族，协议专用地址、主题、符号名等参数应写入 scada_endpoint_param_value。'),
    sa.Column('service_type', sa.String(length=64), nullable=True, comment='服务类型推荐组合：OPC_UA=READ/SUBSCRIBE；MODBUS=TCP_READ/RTU_READ；IEC101=INTERROGATION/SPONTANEOUS；IEC104=INTERROGATION/SPONTANEOUS；IEC61850=MMS_READ/REPORT/GOOSE/SV；MQTT=SUBSCRIBE/PUBLISH；HTTP_REST=REQUEST；BECKHOFF_ADS=ADS_READ_WRITE/ADS_NOTIFICATION。'),
    sa.Column('transport', sa.String(length=32), nullable=False, comment='传输层推荐组合：OPC_UA/MODBUS TCP/IEC104/IEC61850 MMS/BECKHOFF_ADS 用 TCP；MODBUS RTU/IEC101 用 SERIAL；GOOSE/SV 用 ETHERNET_L2；MQTT 用 MQTT；HTTP_REST 用 HTTP 或 HTTPS。'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='主机地址或目标名：TCP/MQTT/HTTP/ADS 填 IP、DNS 或主机名；SERIAL/ETHERNET_L2 可留空并把串口设备、网卡等正式参数写入参数值表。'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口号：OPC_UA 常见 4840，MODBUS TCP 常见 502，IEC104 常见 2404，IEC61850 MMS 常见 102，MQTT 常见 1883/8883，HTTP_REST 常见 80/443，BECKHOFF_ADS 端点通常写 Router 所在主机端口；AMS Port 等正式参数写入参数值表。'),
    sa.Column('namespace_uri', sa.String(length=512), nullable=True, comment='命名空间 URI：主要用于 OPC_UA，填写服务器或业务命名空间，如 urn:windfarm:opcua:wtg；其他协议通常留空。'),
    sa.Column('security_policy', sa.String(length=64), nullable=True, comment='安全策略摘要：OPC_UA 可填 None / Basic256Sha256 等；HTTP_REST 可借此标注 TLS；MQTT/ADS 也可记录站点安全策略摘要。证书路径、TLS 细项等正式参数仍应入参数值表。'),
    sa.Column('security_mode', sa.String(length=64), nullable=True, comment='安全模式摘要：如 None / Sign / SignAndEncrypt / TLS；用于人工识别，不替代正式参数值表。'),
    sa.Column('auth_type', sa.String(length=32), nullable=True, comment='认证方式摘要：Anonymous / UsernamePassword / Certificate / Token / API_KEY；主表只写认证类别，具体用户名、证书引用、Header 名称等写入凭据系统或参数值表。'),
    sa.Column('credential_ref', sa.String(length=255), nullable=True, comment='凭据引用，不直接存明文密码'),
    sa.Column('heartbeat_interval_ms', sa.Integer(), nullable=True, comment='心跳间隔，单位毫秒'),
    sa.Column('service_capabilities_json', sa.JSON(), nullable=False, comment='服务能力摘要，建议写 supports_read / supports_write / supports_subscription / supports_report / supports_batch 等布尔声明；这里只存能力概览，不存协议地址、主题、寄存器、NodeId、ADS symbol 等正式参数。'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='端点说明'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展属性，如 网络区域、冗余组、厂家私有连接字段'),
    sa.Column('record_version', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='乐观并发版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['ied_id'], ['scada_ied.ied_id'], ),
    sa.PrimaryKeyConstraint('endpoint_id'),
    sa.UniqueConstraint('ied_id', 'access_point_name', name='uq_endpoint_ied_ap'),
    comment='通信端点'
    )
    op.create_index(op.f('ix_scada_communication_endpoint_application_protocol'), 'scada_communication_endpoint', ['application_protocol'], unique=False)
    op.create_index(op.f('ix_scada_communication_endpoint_ied_id'), 'scada_communication_endpoint', ['ied_id'], unique=False)
    op.create_index(op.f('ix_scada_communication_endpoint_service_type'), 'scada_communication_endpoint', ['service_type'], unique=False)
    op.create_table('simulation_case',
    sa.Column('simulation_case_id', sa.Integer(), autoincrement=True, nullable=False, comment='仿真案例主键'),
    sa.Column('case_code', sa.String(length=128), nullable=False, comment='案例编码，全局唯一'),
    sa.Column('case_name', sa.String(length=255), nullable=False, comment='案例名称'),
    sa.Column('model_asset_id', sa.Integer(), nullable=False, comment='关联模型资产 ID'),
    sa.Column('case_type', sa.String(length=32), nullable=False, comment='案例类型：DESIGN / OPERATION / FAULT / WHAT_IF / REGRESSION / OTHER'),
    sa.Column('input_file_uri', sa.String(length=1024), nullable=True, comment='输入文件 URI'),
    sa.Column('raw_archive_batch_id', sa.String(length=128), nullable=True, comment='原始归档批次 ID'),
    sa.Column('parameter_json', sa.JSON(), nullable=False, comment='输入参数 JSON，如 wind_speed_mps=12.0'),
    sa.Column('scenario_json', sa.JSON(), nullable=False, comment='场景配置 JSON，如生成停机/偏航/变桨事件'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='案例状态：CREATED / IMPORTED / RUNNING / SUCCEEDED / FAILED / CANCELLED'),
    sa.Column('created_by', sa.String(length=128), nullable=True, comment='创建者标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['model_asset_id'], ['model_asset.model_asset_id'], ),
    sa.PrimaryKeyConstraint('simulation_case_id'),
    sa.UniqueConstraint('case_code', name='uq_simulation_case_code'),
    comment='仿真案例'
    )
    op.create_table('topology_edge',
    sa.Column('edge_id', sa.Integer(), autoincrement=True, nullable=False, comment='拓扑边主键'),
    sa.Column('topology_id', sa.Integer(), nullable=False, comment='所属拓扑图 ID'),
    sa.Column('source_node_id', sa.Integer(), nullable=False, comment='起点节点 ID'),
    sa.Column('target_node_id', sa.Integer(), nullable=False, comment='终点节点 ID'),
    sa.Column('edge_type', sa.String(length=64), nullable=False, comment='边类型：ELECTRICAL_CABLE / FIBER_LINK / ETHERNET_LINK / TRANSFORMER_CONNECTION / SWITCH_CONNECTION'),
    sa.Column('direction', sa.String(length=16), nullable=False, comment='方向：DIRECTED / UNDIRECTED'),
    sa.Column('voltage_level', sa.String(length=32), nullable=True, comment='电压等级，如 35kV / 10kV / 690V，适用电气拓扑'),
    sa.Column('bandwidth_mbps', sa.Float(), nullable=True, comment='链路带宽 (Mbps)，适用通信拓扑'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='边状态：ACTIVE / DISCONNECTED / MAINTENANCE'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展信息，如 线路长度、光纤芯号、开关编号、端口号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_node.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['topology_node.node_id'], ),
    sa.ForeignKeyConstraint(['topology_id'], ['topology_graph.topology_id'], ),
    sa.PrimaryKeyConstraint('edge_id'),
    comment='拓扑边'
    )
    op.create_table('scada_endpoint_param_value',
    sa.Column('endpoint_param_id', sa.Integer(), autoincrement=True, nullable=False, comment='端点参数值主键'),
    sa.Column('endpoint_id', sa.Integer(), nullable=False, comment='通信端点 ID；同一 endpoint 可按多协议服务模板写入多行 key-value 参数值'),
    sa.Column('param_def_id', sa.Integer(), nullable=False, comment='参数定义 ID；通过定义表表达协议/服务/transport 扩展，不在主表加专用列'),
    sa.Column('value_text', sa.String(length=2048), nullable=True, comment='参数值（文本）'),
    sa.Column('value_int', sa.Integer(), nullable=True, comment='参数值（整数）'),
    sa.Column('value_float', sa.Float(), nullable=True, comment='参数值（浮点数）'),
    sa.Column('value_bool', sa.Boolean(), nullable=True, comment='参数值（布尔）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['scada_communication_endpoint.endpoint_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['param_def_id'], ['scada_protocol_param_def.param_def_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('endpoint_param_id'),
    sa.UniqueConstraint('endpoint_id', 'param_def_id', name='uq_endpoint_param_value'),
    comment='通信端点协议参数值'
    )
    op.create_index(op.f('ix_scada_endpoint_param_value_endpoint_id'), 'scada_endpoint_param_value', ['endpoint_id'], unique=False)
    op.create_table('scada_ld_instance',
    sa.Column('ld_instance_id', sa.Integer(), autoincrement=True, nullable=False, comment='LD 实例主键'),
    sa.Column('endpoint_id', sa.Integer(), nullable=False, comment='所属通信端点'),
    sa.Column('asset_instance_id', sa.Integer(), nullable=False, comment='该 LD 实际代表的资产实例，不能为空'),
    sa.Column('signal_profile_id', sa.Integer(), nullable=True, comment='该 LD 使用的点位方案'),
    sa.Column('ld_name', sa.String(length=255), nullable=False, comment='LD 名称，如 ZB-WTG-001 / PCS_001 / MET_001'),
    sa.Column('ld_type', sa.String(length=64), nullable=True, comment='LD 类型：WIND_TURBINE / PCS / BMS / MET_STATION / GATEWAY / SUBSTATION'),
    sa.Column('path_prefix', sa.String(length=512), nullable=True, comment='协议路径前缀，如 WTG_001 / Gateway/WTG_001'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='实例扩展属性'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['endpoint_id'], ['scada_communication_endpoint.endpoint_id'], ),
    sa.ForeignKeyConstraint(['signal_profile_id'], ['scada_signal_profile.signal_profile_id'], ),
    sa.PrimaryKeyConstraint('ld_instance_id'),
    sa.UniqueConstraint('endpoint_id', 'ld_name', name='uq_ld_instance_endpoint_name'),
    comment='LD 实例'
    )
    op.create_index(op.f('ix_scada_ld_instance_asset_instance_id'), 'scada_ld_instance', ['asset_instance_id'], unique=False)
    op.create_index(op.f('ix_scada_ld_instance_endpoint_id'), 'scada_ld_instance', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_scada_ld_instance_signal_profile_id'), 'scada_ld_instance', ['signal_profile_id'], unique=False)
    op.create_table('simulation_result',
    sa.Column('simulation_result_id', sa.Integer(), autoincrement=True, nullable=False, comment='仿真结果主键'),
    sa.Column('simulation_case_id', sa.Integer(), nullable=False, comment='关联仿真案例 ID'),
    sa.Column('result_code', sa.String(length=128), nullable=False, comment='结果编码，全局唯一'),
    sa.Column('result_type', sa.String(length=32), nullable=False, comment='结果类型：TIMESERIES / SUMMARY / REPORT / ARTIFACT / LOG / OTHER'),
    sa.Column('result_file_uri', sa.String(length=1024), nullable=True, comment='结果文件 URI'),
    sa.Column('raw_archive_batch_id', sa.String(length=128), nullable=True, comment='原始归档批次 ID'),
    sa.Column('time_series_backend', sa.String(length=32), nullable=True, comment='时序后端：TDENGINE / FILE / NONE'),
    sa.Column('time_series_ref', sa.String(length=512), nullable=True, comment='时序数据引用（表名或文件路径）'),
    sa.Column('summary_json', sa.JSON(), nullable=False, comment='汇总结果 JSON，如统计指标'),
    sa.Column('metric_json', sa.JSON(), nullable=False, comment='指标 JSON，如性能评估指标'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='结果状态：IMPORTED / PARTIAL / FAILED'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['simulation_case_id'], ['simulation_case.simulation_case_id'], ),
    sa.PrimaryKeyConstraint('simulation_result_id'),
    sa.UniqueConstraint('result_code', name='uq_simulation_result_code'),
    comment='仿真结果'
    )
    op.create_table('acq_signal_sample',
    sa.Column('sample_id', sa.Integer(), autoincrement=True, nullable=False, comment='样本主键'),
    sa.Column('ld_instance_id', sa.Integer(), nullable=False, comment='LD 实例 ID'),
    sa.Column('profile_item_id', sa.Integer(), nullable=False, comment='点位方案明细 ID'),
    sa.Column('asset_instance_id', sa.Integer(), nullable=False, comment='所属资产实例 ID'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='采集任务 ID'),
    sa.Column('resolved_signal_path', sa.String(length=512), nullable=True, comment='实际采集路径'),
    sa.Column('value', sa.Text(), nullable=True, comment='样本值'),
    sa.Column('numeric_value', sa.Float(), nullable=True, comment='数值型冗余值'),
    sa.Column('quality', sa.Integer(), nullable=True, comment='质量位'),
    sa.Column('source_observed_at', sa.DateTime(timezone=True), nullable=True, comment='源端观测时间'),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='平台接收时间'),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False, comment='原始采集载荷'),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['ld_instance_id'], ['scada_ld_instance.ld_instance_id'], ),
    sa.ForeignKeyConstraint(['profile_item_id'], ['scada_signal_profile_item.profile_item_id'], ),
    sa.PrimaryKeyConstraint('sample_id'),
    comment='点位历史样本'
    )
    op.create_index(op.f('ix_acq_signal_sample_asset_instance_id'), 'acq_signal_sample', ['asset_instance_id'], unique=False)
    op.create_table('acq_signal_state',
    sa.Column('signal_state_id', sa.Integer(), autoincrement=True, nullable=False, comment='最新状态主键'),
    sa.Column('ld_instance_id', sa.Integer(), nullable=False, comment='LD 实例 ID'),
    sa.Column('profile_item_id', sa.Integer(), nullable=False, comment='点位方案明细 ID'),
    sa.Column('asset_instance_id', sa.Integer(), nullable=False, comment='所属资产实例 ID，通常冗余自 scada_ld_instance.asset_instance_id，便于查询'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='采集任务 ID'),
    sa.Column('resolved_signal_path', sa.String(length=512), nullable=True, comment='实际解析后的采集路径，如 WTG_001/MMXU1.TotW.mag.f，可由 path_prefix + relative_path 生成'),
    sa.Column('value', sa.Text(), nullable=True, comment='最新值（序列化）'),
    sa.Column('numeric_value', sa.Float(), nullable=True, comment='数值型冗余值，用于统计、告警、排序、聚合'),
    sa.Column('quality', sa.Integer(), nullable=True, comment='质量位，可为空'),
    sa.Column('source_observed_at', sa.DateTime(timezone=True), nullable=True, comment='源端观测时间，可为空'),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='平台接收时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='状态更新时间'),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False, comment='原始采集载荷'),
    sa.ForeignKeyConstraint(['asset_instance_id'], ['asset_instance.asset_instance_id'], ),
    sa.ForeignKeyConstraint(['ld_instance_id'], ['scada_ld_instance.ld_instance_id'], ),
    sa.ForeignKeyConstraint(['profile_item_id'], ['scada_signal_profile_item.profile_item_id'], ),
    sa.PrimaryKeyConstraint('signal_state_id'),
    sa.UniqueConstraint('ld_instance_id', 'profile_item_id', name='uq_signal_state'),
    comment='点位最新状态'
    )
    op.create_index(op.f('ix_acq_signal_state_asset_instance_id'), 'acq_signal_state', ['asset_instance_id'], unique=False)
    op.create_table('acq_task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False, comment='采集任务主键'),
    sa.Column('task_name', sa.String(length=255), nullable=False, comment='采集任务名称，如 task_ZB-WTG-001'),
    sa.Column('ld_instance_id', sa.Integer(), nullable=False, comment='LD 实例 ID，采集任务的核心对象；通过它可确定 endpoint、asset_instance、signal_profile'),
    sa.Column('acquisition_mode', sa.String(length=32), nullable=False, comment='采集模式：READ_ONCE / POLLING / SUBSCRIBE / REPORT'),
    sa.Column('task_status', sa.String(length=16), nullable=False, comment='任务生命周期状态：STARTED / RUNNING / STOPPING / ERROR / SUCCESS / STOPPED'),
    sa.Column('request_timeout_ms', sa.Integer(), nullable=False, comment='单次 read 请求超时，单位毫秒'),
    sa.Column('poll_interval_ms', sa.Integer(), nullable=False, comment='采集轮询周期，单位毫秒'),
    sa.Column('polling_max_concurrent_connections', sa.Integer(), nullable=False, comment='POLLING/READ_ONCE 主动采集时允许同时读取的最大 connection 数；不拆分 items'),
    sa.Column('polling_connection_start_interval_ms', sa.Integer(), nullable=False, comment='POLLING/READ_ONCE 主动采集时不同 connection 的启动错峰间隔，单位毫秒；不改变单 connection 采样周期'),
    sa.Column('subscription_start_interval_ms', sa.Integer(), nullable=False, comment='SUBSCRIBE 模式下不同 connection 启动订阅的错峰间隔，单位毫秒'),
    sa.Column('subscription_notification_queue_size', sa.Integer(), nullable=False, comment='SUBSCRIBE 模式下客户端侧 notification 队列容量；队列满表示客户端过载'),
    sa.Column('subscription_notification_worker_count', sa.Integer(), nullable=False, comment='SUBSCRIBE 模式下客户端侧 notification 固定消费 worker 数'),
    sa.Column('subscription_notification_max_lag_ms', sa.Integer(), nullable=False, comment='SUBSCRIBE 模式下 notification 在客户端队列中的最大允许等待时间，单位毫秒；超限表示处理滞后'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='配置态启停标记，不表示运行状态'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='任务优先级，数值越小优先级越高'),
    sa.Column('partition_key', sa.String(length=128), nullable=True, comment='多节点分区键，用于 dual_active_partitioned'),
    sa.Column('assignment_policy', sa.String(length=32), nullable=False, comment='任务分配策略：AUTO / PINNED / DISABLED'),
    sa.Column('version', sa.Integer(), nullable=False, comment='乐观并发控制版本号'),
    sa.Column('freshness_timeout_ms', sa.Integer(), nullable=False, comment='数据新鲜度超时(ms)，用于判断 latest-state 是否 stale；polling/read 模式主要使用'),
    sa.Column('alive_timeout_ms', sa.Integer(), nullable=False, comment='链路存活超时(ms)，subscribe 模式主要使用；polling 模式也可用于判断 source 是否连续失败导致 offline'),
    sa.Column('protocol_params', sa.JSON(), nullable=False, comment='协议专属参数，避免 acq_task 被 OPC UA / Modbus / IEC 61850 字段污染'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.CheckConstraint("acquisition_mode IN ('READ_ONCE', 'POLLING', 'SUBSCRIBE', 'REPORT')", name='ck_acq_task_acquisition_mode'),
    sa.CheckConstraint("task_status IN ('STARTED', 'RUNNING', 'STOPPING', 'ERROR', 'SUCCESS', 'STOPPED')", name='ck_acq_task_status'),
    sa.CheckConstraint('polling_connection_start_interval_ms >= 0', name='ck_acq_task_polling_connection_start_interval_ms'),
    sa.CheckConstraint('polling_max_concurrent_connections > 0', name='ck_acq_task_polling_max_concurrent_connections'),
    sa.CheckConstraint('subscription_notification_max_lag_ms > 0', name='ck_acq_task_subscription_notification_max_lag_ms'),
    sa.CheckConstraint('subscription_notification_queue_size > 0', name='ck_acq_task_subscription_notification_queue_size'),
    sa.CheckConstraint('subscription_notification_worker_count > 0', name='ck_acq_task_subscription_notification_worker_count'),
    sa.CheckConstraint('subscription_start_interval_ms >= 0', name='ck_acq_task_subscription_start_interval_ms'),
    sa.ForeignKeyConstraint(['ld_instance_id'], ['scada_ld_instance.ld_instance_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('ld_instance_id', 'acquisition_mode', name='uq_acq_task_ld_mode'),
    sa.UniqueConstraint('task_name'),
    comment='采集任务配置'
    )
    op.create_index(op.f('ix_acq_task_ld_instance_id'), 'acq_task', ['ld_instance_id'], unique=False)
    op.create_table('ingest_runtime_event',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False, comment='事件主键'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='事件类型：CONFIG_INVALID / ACQUISITION_FAILED / CACHE_UPDATE_FAILED / SNAPSHOT_INVALID / PUBLISH_FAILED / RECOVERED 等'),
    sa.Column('failure_category', sa.String(length=64), nullable=True, comment='失败类别'),
    sa.Column('severity', sa.String(length=32), nullable=False, comment='严重级别：INFO / WARNING / ERROR / CRITICAL'),
    sa.Column('task_id', sa.Integer(), nullable=True, comment='关联采集任务'),
    sa.Column('ld_instance_id', sa.Integer(), nullable=True, comment='LD 实例 ID，冗余保存便于按设备查故障'),
    sa.Column('acquisition_mode', sa.String(length=32), nullable=True, comment='采集模式'),
    sa.Column('stage', sa.String(length=64), nullable=False, comment='发生阶段：VALIDATION / PLAN_BUILD / SCHEDULER / ACQUISITION / CACHE_UPDATE / SUBSCRIBE / SNAPSHOT_READ / SNAPSHOT_VALIDATE / SNAPSHOT_ASSEMBLE / PUBLISH'),
    sa.Column('protocol', sa.String(length=32), nullable=True, comment='协议：OPCUA / MODBUS / IEC61850'),
    sa.Column('error_code', sa.String(length=128), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('exception_type', sa.String(length=255), nullable=True, comment='异常类型'),
    sa.Column('traceback_hash', sa.String(length=128), nullable=True, comment='traceback 哈希，便于归并，完整 traceback 仍交日志系统'),
    sa.Column('retryable', sa.Boolean(), nullable=False, comment='是否可重试'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='发生时间'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='解决时间，RECOVERED 事件必须填写'),
    sa.Column('attributes_json', sa.JSON(), nullable=False, comment='扩展信息'),
    sa.ForeignKeyConstraint(['task_id'], ['acq_task.task_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    comment='采集运行时事件'
    )
    op.create_index(op.f('ix_ingest_runtime_event_task_id'), 'ingest_runtime_event', ['task_id'], unique=False)
    op.create_index('ix_runtime_event_category_time', 'ingest_runtime_event', ['failure_category', 'occurred_at'], unique=False)
    op.create_index('ix_runtime_event_ld_time', 'ingest_runtime_event', ['ld_instance_id', 'occurred_at'], unique=False)
    op.create_index('ix_runtime_event_severity_time', 'ingest_runtime_event', ['severity', 'occurred_at'], unique=False)
    op.create_index('ix_runtime_event_stage_time', 'ingest_runtime_event', ['stage', 'occurred_at'], unique=False)
    op.create_index('ix_runtime_event_task_time', 'ingest_runtime_event', ['task_id', 'occurred_at'], unique=False)
    op.create_index('ix_runtime_event_type_time', 'ingest_runtime_event', ['event_type', 'occurred_at'], unique=False)
    op.create_table('ingest_runtime_job',
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('partition_key', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('schedule_kind', sa.String(length=32), nullable=False),
    sa.Column('schedule_expr', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['acq_task.task_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_ingest_runtime_job_task_id'), 'ingest_runtime_job', ['task_id'], unique=False)
    op.create_table('ingest_source_health',
    sa.Column('health_id', sa.Integer(), autoincrement=True, nullable=False, comment='健康记录主键'),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='采集任务 ID，每个 acq_task 对应一条 health'),
    sa.Column('ld_instance_id', sa.Integer(), nullable=False, comment='LD 实例 ID，冗余保存便于按设备查询'),
    sa.Column('acquisition_mode', sa.String(length=32), nullable=False, comment='采集模式：READ_ONCE / POLLING / SUBSCRIBE'),
    sa.Column('health_status', sa.String(length=32), nullable=False, comment='健康状态：UNKNOWN / HEALTHY / DEGRADED / OFFLINE'),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次采集成功时间'),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次失败时间'),
    sa.Column('last_alive_at', sa.DateTime(timezone=True), nullable=True, comment='最近一次确认采集链路仍然活着的时间；subscribe 模式使用 datachange/keep-alive/watchdog 更新'),
    sa.Column('last_datachange_at', sa.DateTime(timezone=True), nullable=True, comment='subscribe 模式最近一次 datachange 时间；值长期不变时该字段可能不更新，不应单独用于判断失活'),
    sa.Column('consecutive_failure_count', sa.Integer(), nullable=False, comment='连续失败次数，成功后清零'),
    sa.Column('total_failure_count', sa.BigInteger(), nullable=False, comment='累计失败次数'),
    sa.Column('last_failure_category', sa.String(length=64), nullable=True, comment='最近一次失败类别：SOURCE_UNAVAILABLE / SOURCE_TIMEOUT / DATA_INVALID 等'),
    sa.Column('last_error_code', sa.String(length=128), nullable=True, comment='最近一次错误码'),
    sa.Column('last_error_message', sa.Text(), nullable=True, comment='最近一次错误信息'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['ld_instance_id'], ['scada_ld_instance.ld_instance_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['acq_task.task_id'], ),
    sa.PrimaryKeyConstraint('health_id'),
    comment='采集源健康状态'
    )
    op.create_index(op.f('ix_ingest_source_health_ld_instance_id'), 'ingest_source_health', ['ld_instance_id'], unique=False)
    op.create_index(op.f('ix_ingest_source_health_task_id'), 'ingest_source_health', ['task_id'], unique=True)
    op.create_index('ix_source_health_alive_at', 'ingest_source_health', ['last_alive_at'], unique=False)
    op.create_index('ix_source_health_failure_at', 'ingest_source_health', ['last_failure_at'], unique=False)
    op.create_index('ix_source_health_ld_instance', 'ingest_source_health', ['ld_instance_id'], unique=False)
    op.create_index('ix_source_health_status', 'ingest_source_health', ['health_status'], unique=False)
    op.create_table('ingest_job_assignment',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('assignment_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingest_runtime_job.job_id'], ),
    sa.ForeignKeyConstraint(['node_key'], ['ingest_runtime_node.node_key'], ),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('job_id', 'node_key', name='uq_ingest_job_assignment_job_node')
    )
    op.create_index(op.f('ix_ingest_job_assignment_job_id'), 'ingest_job_assignment', ['job_id'], unique=False)
    op.create_index(op.f('ix_ingest_job_assignment_node_key'), 'ingest_job_assignment', ['node_key'], unique=False)
    # ### end Alembic commands ###


def downgrade_whale() -> None:
    """Downgrade whale schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_job_assignment_node_key'), table_name='ingest_job_assignment')
    op.drop_index(op.f('ix_ingest_job_assignment_job_id'), table_name='ingest_job_assignment')
    op.drop_table('ingest_job_assignment')
    op.drop_index('ix_source_health_status', table_name='ingest_source_health')
    op.drop_index('ix_source_health_ld_instance', table_name='ingest_source_health')
    op.drop_index('ix_source_health_failure_at', table_name='ingest_source_health')
    op.drop_index('ix_source_health_alive_at', table_name='ingest_source_health')
    op.drop_index(op.f('ix_ingest_source_health_task_id'), table_name='ingest_source_health')
    op.drop_index(op.f('ix_ingest_source_health_ld_instance_id'), table_name='ingest_source_health')
    op.drop_table('ingest_source_health')
    op.drop_index(op.f('ix_ingest_runtime_job_task_id'), table_name='ingest_runtime_job')
    op.drop_table('ingest_runtime_job')
    op.drop_index('ix_runtime_event_type_time', table_name='ingest_runtime_event')
    op.drop_index('ix_runtime_event_task_time', table_name='ingest_runtime_event')
    op.drop_index('ix_runtime_event_stage_time', table_name='ingest_runtime_event')
    op.drop_index('ix_runtime_event_severity_time', table_name='ingest_runtime_event')
    op.drop_index('ix_runtime_event_ld_time', table_name='ingest_runtime_event')
    op.drop_index('ix_runtime_event_category_time', table_name='ingest_runtime_event')
    op.drop_index(op.f('ix_ingest_runtime_event_task_id'), table_name='ingest_runtime_event')
    op.drop_table('ingest_runtime_event')
    op.drop_index(op.f('ix_acq_task_ld_instance_id'), table_name='acq_task')
    op.drop_table('acq_task')
    op.drop_index(op.f('ix_acq_signal_state_asset_instance_id'), table_name='acq_signal_state')
    op.drop_table('acq_signal_state')
    op.drop_index(op.f('ix_acq_signal_sample_asset_instance_id'), table_name='acq_signal_sample')
    op.drop_table('acq_signal_sample')
    op.drop_table('simulation_result')
    op.drop_index(op.f('ix_scada_ld_instance_signal_profile_id'), table_name='scada_ld_instance')
    op.drop_index(op.f('ix_scada_ld_instance_endpoint_id'), table_name='scada_ld_instance')
    op.drop_index(op.f('ix_scada_ld_instance_asset_instance_id'), table_name='scada_ld_instance')
    op.drop_table('scada_ld_instance')
    op.drop_index(op.f('ix_scada_endpoint_param_value_endpoint_id'), table_name='scada_endpoint_param_value')
    op.drop_table('scada_endpoint_param_value')
    op.drop_table('topology_edge')
    op.drop_table('simulation_case')
    op.drop_index(op.f('ix_scada_communication_endpoint_service_type'), table_name='scada_communication_endpoint')
    op.drop_index(op.f('ix_scada_communication_endpoint_ied_id'), table_name='scada_communication_endpoint')
    op.drop_index(op.f('ix_scada_communication_endpoint_application_protocol'), table_name='scada_communication_endpoint')
    op.drop_table('scada_communication_endpoint')
    op.drop_table('topology_node')
    op.drop_index(op.f('ix_scada_signal_profile_item_param_value_profile_item_id'), table_name='scada_signal_profile_item_param_value')
    op.drop_table('scada_signal_profile_item_param_value')
    op.drop_index(op.f('ix_scada_ied_asset_instance_id'), table_name='scada_ied')
    op.drop_table('scada_ied')
    op.drop_table('model_asset')
    op.drop_table('asset_relation')
    op.drop_index(op.f('ix_scada_signal_profile_item_signal_profile_id'), table_name='scada_signal_profile_item')
    op.drop_table('scada_signal_profile_item')
    op.drop_index(op.f('ix_asset_instance_parent_asset_instance_id'), table_name='asset_instance')
    op.drop_index(op.f('ix_asset_instance_asset_type_id'), table_name='asset_instance')
    op.drop_table('asset_instance')
    op.drop_table('asset_bom')
    op.drop_table('scada_signal_profile')
    op.drop_table('asset_model')
    op.drop_table('asset_attribute')
    op.drop_table('topology_graph')
    op.drop_table('simulation_artifact')
    op.drop_table('scada_signal_param_def')
    op.drop_table('scada_protocol_param_def')
    op.drop_table('scada_fc_dict')
    op.drop_table('scada_data_type')
    op.drop_table('scada_cdc_dict')
    op.drop_index(op.f('ix_org_unit_parent_org_id'), table_name='org_unit')
    op.drop_table('org_unit')
    op.drop_table('ingest_runtime_node')
    op.drop_table('ingest_runtime_config_version')
    op.drop_index(op.f('ix_ingest_job_lease_resource_id'), table_name='ingest_job_lease')
    op.drop_index(op.f('ix_ingest_job_lease_holder_key'), table_name='ingest_job_lease')
    op.drop_table('ingest_job_lease')
    op.drop_index(op.f('ix_ingest_idempotency_record_idempotency_key'), table_name='ingest_idempotency_record')
    op.drop_table('ingest_idempotency_record')
    op.drop_table('ingest_fencing_token')
    op.drop_table('ingest_bundle_metadata')
    op.drop_index(op.f('ix_ingest_audit_event_request_id'), table_name='ingest_audit_event')
    op.drop_table('ingest_audit_event')
    op.drop_table('asset_type')
    # ### end Alembic commands ###

